# -*- coding: utf-8 -*-
"""FSP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uTfiGhv08xVA1cgCnzpYfbzDb0ahRNd
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import glob
import os

# 1. Caminho da pasta no seu Google Drive (certifique-se de que o nome é igual)
caminho_pasta = '/content/drive/MyDrive/Siconfi_Dados'

# 2. Pega todos os arquivos CSV dentro da pasta
arquivos_csv = glob.glob(os.path.join(caminho_pasta, "*.csv"))

# 3. Códigos IBGE das suas cidades (Santana/AP e Garanhuns/PE)
cidades_alvo = [1600600, 2606002]

lista_dados_filtrados = []

print("Iniciando a extração dos dados...")

# 4. O Loop
for arquivo in arquivos_csv:
    try:
        df = pd.read_csv(arquivo, sep=';', encoding='latin-1', skiprows=3)

        coluna_ibge = 'Cod.IBGE' if 'Cod.IBGE' in df.columns else 'Cod. IBGE'

        # Filtra pelas cidades
        df_filtrado = df[df[coluna_ibge].isin(cidades_alvo)]

        # Pega o ano do nome do arquivo
        ano_arquivo = ''.join(filter(str.isdigit, os.path.basename(arquivo)))
        df_filtrado['Ano'] = ano_arquivo

        lista_dados_filtrados.append(df_filtrado)
        print(f"✅ Arquivo {os.path.basename(arquivo)} processado com sucesso!")

    except Exception as e:
        print(f"❌ Erro ao processar {os.path.basename(arquivo)}: {e}")

# 5. Junta tudo
if lista_dados_filtrados:
    df_final = pd.concat(lista_dados_filtrados, ignore_index=True)

    # 6. Salva o resultado no seu Drive
    caminho_saida = '/content/drive/MyDrive/dados_consolidados_trabalho.xlsx'
    df_final.to_excel(caminho_saida, index=False)

    print(f"\n🎉 Extração concluída! O arquivo foi salvo no seu Drive em: {caminho_saida}")
else:
    print("\n⚠️ Nenhum dado foi encontrado. Verifique se os arquivos CSV estão na pasta correta.")